-- H2（MySQL 兼容模式）建表脚本，启动时自动执行
CREATE TABLE IF NOT EXISTS fan_board (
    slot       INT PRIMARY KEY,
    speed      VARCHAR(16) NOT NULL,
    mode       VARCHAR(16) NOT NULL,
    updated_at TIMESTAMP   NOT NULL
);

CREATE TABLE IF NOT EXISTS business_board (
    slot       INT PRIMARY KEY,
    temperature DOUBLE NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS alarm_record (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot       INT NOT NULL,
    temperature DOUBLE NOT NULL,
    alarm_time TIMESTAMP NOT NULL
);
